/**
 * Tool Definitions - Batch 1
 * Categories: naming-conventions, encoding, crypto, formatters
 * Total: 61 tools
 */

import type { Tool } from '../types';

/**
 * Naming Convention Tools (14 tools)
 */
export const NAMING_CONVENTION_TOOLS: Tool[] = [
  {
    id: 'to-camel-case',
    name: 'To camelCase',
    description: 'Convert text to camelCase format (e.g., myVariableName)',
    categoryId: 'naming-conventions',
    slug: 'to-camel-case',
    transformFn: 'toCamelCase',
    keywords: ['camel', 'case', 'variable', 'javascript', 'naming'],
    inputPlaceholder: 'Enter text like "hello world" or "hello_world"...',
  },
  {
    id: 'to-pascal-case',
    name: 'To PascalCase',
    description: 'Convert text to PascalCase format (e.g., MyClassName)',
    categoryId: 'naming-conventions',
    slug: 'to-pascal-case',
    transformFn: 'toPascalCase',
    keywords: ['pascal', 'case', 'class', 'component', 'naming'],
    inputPlaceholder: 'Enter text like "hello world" or "hello-world"...',
  },
  {
    id: 'to-snake-case',
    name: 'To snake_case',
    description: 'Convert text to snake_case format (e.g., my_variable_name)',
    categoryId: 'naming-conventions',
    slug: 'to-snake-case',
    transformFn: 'toSnakeCase',
    keywords: ['snake', 'case', 'python', 'database', 'naming'],
    inputPlaceholder: 'Enter text like "Hello World" or "helloWorld"...',
  },
  {
    id: 'to-screaming-snake-case',
    name: 'To SCREAMING_SNAKE_CASE',
    description: 'Convert text to SCREAMING_SNAKE_CASE format (e.g., MY_CONSTANT)',
    categoryId: 'naming-conventions',
    slug: 'to-screaming-snake-case',
    transformFn: 'toScreamingSnakeCase',
    keywords: ['screaming', 'snake', 'case', 'constant', 'env', 'naming'],
    inputPlaceholder: 'Enter text like "api key" or "maxRetries"...',
  },
  {
    id: 'to-kebab-case',
    name: 'To kebab-case',
    description: 'Convert text to kebab-case format (e.g., my-css-class)',
    categoryId: 'naming-conventions',
    slug: 'to-kebab-case',
    transformFn: 'toKebabCase',
    keywords: ['kebab', 'case', 'css', 'url', 'slug', 'naming'],
    inputPlaceholder: 'Enter text like "Hello World" or "myClass"...',
  },
  {
    id: 'to-train-case',
    name: 'To Train-Case',
    description: 'Convert text to Train-Case format (e.g., My-Header-Name)',
    categoryId: 'naming-conventions',
    slug: 'to-train-case',
    transformFn: 'toTrainCase',
    keywords: ['train', 'case', 'http', 'header', 'naming'],
    inputPlaceholder: 'Enter text like "content type" or "user_agent"...',
  },
  {
    id: 'to-dot-case',
    name: 'To dot.case',
    description: 'Convert text to dot.case format (e.g., my.config.key)',
    categoryId: 'naming-conventions',
    slug: 'to-dot-case',
    transformFn: 'toDotCase',
    keywords: ['dot', 'case', 'config', 'property', 'naming'],
    inputPlaceholder: 'Enter text like "database host" or "api_key"...',
  },
  {
    id: 'to-path-case',
    name: 'To path/case',
    description: 'Convert text to path/case format (e.g., my/file/path)',
    categoryId: 'naming-conventions',
    slug: 'to-path-case',
    transformFn: 'toPathCase',
    keywords: ['path', 'case', 'file', 'directory', 'naming'],
    inputPlaceholder: 'Enter text like "user profile page" or "api_endpoint"...',
  },
  {
    id: 'to-namespace-case',
    name: 'To Namespace::Case',
    description: 'Convert text to Namespace::Case format (e.g., My::Module::Name)',
    categoryId: 'naming-conventions',
    slug: 'to-namespace-case',
    transformFn: 'toNamespaceCase',
    keywords: ['namespace', 'case', 'ruby', 'php', 'module', 'naming'],
    inputPlaceholder: 'Enter text like "app controllers users" or "api-v2"...',
  },
  {
    id: 'to-ada-case',
    name: 'To Ada_Case',
    description: 'Convert text to Ada_Case format (e.g., My_Variable_Name)',
    categoryId: 'naming-conventions',
    slug: 'to-ada-case',
    transformFn: 'toAdaCase',
    keywords: ['ada', 'case', 'programming', 'naming'],
    inputPlaceholder: 'Enter text like "hello world" or "maxValue"...',
  },
  {
    id: 'to-cobol-case',
    name: 'To COBOL-CASE',
    description: 'Convert text to COBOL-CASE format (e.g., MY-VARIABLE-NAME)',
    categoryId: 'naming-conventions',
    slug: 'to-cobol-case',
    transformFn: 'toCobolCase',
    keywords: ['cobol', 'case', 'legacy', 'mainframe', 'naming'],
    inputPlaceholder: 'Enter text like "customer id" or "orderTotal"...',
  },
  {
    id: 'to-flat-case',
    name: 'To flatcase',
    description: 'Convert text to flatcase format (e.g., myvariablename)',
    categoryId: 'naming-conventions',
    slug: 'to-flat-case',
    transformFn: 'toFlatCase',
    keywords: ['flat', 'case', 'lowercase', 'naming'],
    inputPlaceholder: 'Enter text like "Hello World" or "my-variable"...',
  },
  {
    id: 'to-upper-flat-case',
    name: 'To UPPERFLATCASE',
    description: 'Convert text to UPPERFLATCASE format (e.g., MYVARIABLENAME)',
    categoryId: 'naming-conventions',
    slug: 'to-upper-flat-case',
    transformFn: 'toUpperFlatCase',
    keywords: ['upper', 'flat', 'case', 'uppercase', 'naming'],
    inputPlaceholder: 'Enter text like "Hello World" or "my-variable"...',
  },
  {
    id: 'detect-naming-convention',
    name: 'Detect Naming Convention',
    description: 'Automatically detect the naming convention of input text',
    categoryId: 'naming-conventions',
    slug: 'detect-naming-convention',
    transformFn: 'detectNamingConvention',
    keywords: ['detect', 'identify', 'analyze', 'naming', 'convention'],
    inputPlaceholder: 'Enter text like "myVariableName" or "my_variable_name"...',
    outputPlaceholder: 'Detected convention will appear here...',
  },
];

/**
 * Encoding Tools (16 tools)
 */
export const ENCODING_TOOLS: Tool[] = [
  {
    id: 'base64-encode',
    name: 'Base64 Encode',
    description: 'Encode text to Base64 format',
    categoryId: 'encoding',
    slug: 'base64-encode',
    transformFn: 'base64Encode',
    reverseFn: 'base64Decode',
    keywords: ['base64', 'encode', 'binary', 'data'],
    inputPlaceholder: 'Enter text to encode...',
  },
  {
    id: 'base64-decode',
    name: 'Base64 Decode',
    description: 'Decode Base64 encoded text back to original',
    categoryId: 'encoding',
    slug: 'base64-decode',
    transformFn: 'base64Decode',
    reverseFn: 'base64Encode',
    keywords: ['base64', 'decode', 'binary', 'data'],
    inputPlaceholder: 'Enter Base64 text to decode (e.g., SGVsbG8gV29ybGQ=)...',
  },
  {
    id: 'base32-encode',
    name: 'Base32 Encode',
    description: 'Encode text to Base32 format',
    categoryId: 'encoding',
    slug: 'base32-encode',
    transformFn: 'base32Encode',
    reverseFn: 'base32Decode',
    keywords: ['base32', 'encode', 'binary'],
    inputPlaceholder: 'Enter text to encode...',
  },
  {
    id: 'base32-decode',
    name: 'Base32 Decode',
    description: 'Decode Base32 encoded text back to original',
    categoryId: 'encoding',
    slug: 'base32-decode',
    transformFn: 'base32Decode',
    reverseFn: 'base32Encode',
    keywords: ['base32', 'decode', 'binary'],
    inputPlaceholder: 'Enter Base32 text to decode...',
  },
  {
    id: 'url-encode',
    name: 'URL Encode',
    description: 'Encode text for safe use in URLs (percent encoding)',
    categoryId: 'encoding',
    slug: 'url-encode',
    transformFn: 'urlEncode',
    reverseFn: 'urlDecode',
    keywords: ['url', 'encode', 'percent', 'uri', 'web'],
    inputPlaceholder: 'Enter text to URL encode...',
  },
  {
    id: 'url-decode',
    name: 'URL Decode',
    description: 'Decode URL encoded (percent encoded) text',
    categoryId: 'encoding',
    slug: 'url-decode',
    transformFn: 'urlDecode',
    reverseFn: 'urlEncode',
    keywords: ['url', 'decode', 'percent', 'uri', 'web'],
    inputPlaceholder: 'Enter URL encoded text (e.g., Hello%20World)...',
  },
  {
    id: 'html-encode',
    name: 'HTML Encode',
    description: 'Encode special characters as HTML entities',
    categoryId: 'encoding',
    slug: 'html-encode',
    transformFn: 'htmlEncode',
    reverseFn: 'htmlDecode',
    keywords: ['html', 'encode', 'entities', 'escape', 'xss'],
    inputPlaceholder: 'Enter text with special characters (e.g., <script>)...',
  },
  {
    id: 'html-decode',
    name: 'HTML Decode',
    description: 'Decode HTML entities back to characters',
    categoryId: 'encoding',
    slug: 'html-decode',
    transformFn: 'htmlDecode',
    reverseFn: 'htmlEncode',
    keywords: ['html', 'decode', 'entities', 'unescape'],
    inputPlaceholder: 'Enter HTML encoded text (e.g., &lt;div&gt;)...',
  },
  {
    id: 'text-to-binary',
    name: 'Text to Binary',
    description: 'Convert text to binary representation (0s and 1s)',
    categoryId: 'encoding',
    slug: 'text-to-binary',
    transformFn: 'textToBinary',
    reverseFn: 'binaryToText',
    keywords: ['binary', 'encode', 'bits', 'text'],
    inputPlaceholder: 'Enter text to convert to binary...',
  },
  {
    id: 'binary-to-text',
    name: 'Binary to Text',
    description: 'Convert binary (0s and 1s) back to text',
    categoryId: 'encoding',
    slug: 'binary-to-text',
    transformFn: 'binaryToText',
    reverseFn: 'textToBinary',
    keywords: ['binary', 'decode', 'bits', 'text'],
    inputPlaceholder: 'Enter binary (e.g., 01001000 01101001)...',
  },
  {
    id: 'text-to-hex',
    name: 'Text to Hex',
    description: 'Convert text to hexadecimal representation',
    categoryId: 'encoding',
    slug: 'text-to-hex',
    transformFn: 'textToHex',
    reverseFn: 'hexToText',
    keywords: ['hex', 'hexadecimal', 'encode', 'text'],
    inputPlaceholder: 'Enter text to convert to hex...',
  },
  {
    id: 'hex-to-text',
    name: 'Hex to Text',
    description: 'Convert hexadecimal back to text',
    categoryId: 'encoding',
    slug: 'hex-to-text',
    transformFn: 'hexToText',
    reverseFn: 'textToHex',
    keywords: ['hex', 'hexadecimal', 'decode', 'text'],
    inputPlaceholder: 'Enter hex (e.g., 48656c6c6f)...',
  },
  {
    id: 'utf8-encode',
    name: 'UTF-8 Encode',
    description: 'Encode text as UTF-8 byte sequence (shown as hex)',
    categoryId: 'encoding',
    slug: 'utf8-encode',
    transformFn: 'utf8Encode',
    reverseFn: 'utf8Decode',
    keywords: ['utf8', 'utf-8', 'unicode', 'encode', 'bytes'],
    inputPlaceholder: 'Enter text with unicode characters...',
  },
  {
    id: 'utf8-decode',
    name: 'UTF-8 Decode',
    description: 'Decode UTF-8 byte sequence back to text',
    categoryId: 'encoding',
    slug: 'utf8-decode',
    transformFn: 'utf8Decode',
    reverseFn: 'utf8Encode',
    keywords: ['utf8', 'utf-8', 'unicode', 'decode', 'bytes'],
    inputPlaceholder: 'Enter UTF-8 hex bytes (e.g., c3a9)...',
  },
  {
    id: 'text-to-ascii',
    name: 'Text to ASCII Codes',
    description: 'Convert text to ASCII code numbers',
    categoryId: 'encoding',
    slug: 'text-to-ascii',
    transformFn: 'textToAscii',
    reverseFn: 'asciiToText',
    keywords: ['ascii', 'codes', 'numbers', 'encode'],
    inputPlaceholder: 'Enter text to get ASCII codes...',
  },
  {
    id: 'ascii-to-text',
    name: 'ASCII Codes to Text',
    description: 'Convert ASCII code numbers back to text',
    categoryId: 'encoding',
    slug: 'ascii-to-text',
    transformFn: 'asciiToText',
    reverseFn: 'textToAscii',
    keywords: ['ascii', 'codes', 'numbers', 'decode'],
    inputPlaceholder: 'Enter ASCII codes (e.g., 72 101 108 108 111)...',
  },
];

/**
 * Crypto Tools (13 tools)
 */
export const CRYPTO_TOOLS: Tool[] = [
  {
    id: 'md5-hash',
    name: 'MD5 Hash',
    description: 'Generate MD5 hash of input text (128-bit)',
    categoryId: 'crypto',
    slug: 'md5-hash',
    transformFn: 'md5Hash',
    isAsync: true,
    keywords: ['md5', 'hash', 'checksum', 'fingerprint'],
    inputPlaceholder: 'Enter text to hash...',
    outputPlaceholder: '32-character hex hash will appear here...',
  },
  {
    id: 'sha1-hash',
    name: 'SHA-1 Hash',
    description: 'Generate SHA-1 hash of input text (160-bit)',
    categoryId: 'crypto',
    slug: 'sha1-hash',
    transformFn: 'sha1Hash',
    isAsync: true,
    keywords: ['sha1', 'sha-1', 'hash', 'checksum'],
    inputPlaceholder: 'Enter text to hash...',
    outputPlaceholder: '40-character hex hash will appear here...',
  },
  {
    id: 'sha256-hash',
    name: 'SHA-256 Hash',
    description: 'Generate SHA-256 hash of input text (256-bit)',
    categoryId: 'crypto',
    slug: 'sha256-hash',
    transformFn: 'sha256Hash',
    isAsync: true,
    keywords: ['sha256', 'sha-256', 'hash', 'secure', 'checksum'],
    inputPlaceholder: 'Enter text to hash...',
    outputPlaceholder: '64-character hex hash will appear here...',
  },
  {
    id: 'sha512-hash',
    name: 'SHA-512 Hash',
    description: 'Generate SHA-512 hash of input text (512-bit)',
    categoryId: 'crypto',
    slug: 'sha512-hash',
    transformFn: 'sha512Hash',
    isAsync: true,
    keywords: ['sha512', 'sha-512', 'hash', 'secure', 'checksum'],
    inputPlaceholder: 'Enter text to hash...',
    outputPlaceholder: '128-character hex hash will appear here...',
  },
  {
    id: 'generate-uuid',
    name: 'Generate UUID v4',
    description: 'Generate a random UUID v4 (universally unique identifier)',
    categoryId: 'crypto',
    slug: 'generate-uuid',
    transformFn: 'generateUUIDv4',
    isGenerator: true,
    keywords: ['uuid', 'guid', 'unique', 'identifier', 'random'],
    options: [
      {
        key: 'count',
        label: 'How Many',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
    ],
    inputPlaceholder: 'Click Generate to create UUIDs...',
    outputPlaceholder: 'UUIDs will appear here...',
  },
  {
    id: 'generate-ulid',
    name: 'Generate ULID',
    description: 'Generate a ULID (Universally Unique Lexicographically Sortable Identifier)',
    categoryId: 'crypto',
    slug: 'generate-ulid',
    transformFn: 'generateULID',
    isGenerator: true,
    keywords: ['ulid', 'unique', 'identifier', 'sortable', 'random'],
    options: [
      {
        key: 'count',
        label: 'How Many',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
    ],
    inputPlaceholder: 'Click Generate to create ULIDs...',
    outputPlaceholder: 'ULIDs will appear here...',
  },
  {
    id: 'generate-nanoid',
    name: 'Generate NanoID',
    description: 'Generate a compact, URL-safe unique ID',
    categoryId: 'crypto',
    slug: 'generate-nanoid',
    transformFn: 'generateNanoID',
    isGenerator: true,
    keywords: ['nanoid', 'unique', 'identifier', 'compact', 'random'],
    options: [
      {
        key: 'count',
        label: 'How Many',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
      {
        key: 'size',
        label: 'Length',
        type: 'number',
        defaultValue: 21,
        min: 1,
        max: 100,
      },
    ],
    inputPlaceholder: 'Click Generate to create NanoIDs...',
    outputPlaceholder: 'NanoIDs will appear here...',
  },
  {
    id: 'decode-jwt',
    name: 'Decode JWT',
    description: 'Decode and display the contents of a JWT token',
    categoryId: 'crypto',
    slug: 'decode-jwt',
    transformFn: 'decodeJWT',
    keywords: ['jwt', 'token', 'decode', 'json', 'auth', 'bearer'],
    inputPlaceholder: 'Paste a JWT token (e.g., eyJhbGciOiJIUzI1NiIs...)...',
    outputPlaceholder: 'Decoded header and payload will appear here...',
  },
  {
    id: 'hmac-sha256',
    name: 'HMAC SHA-256',
    description: 'Generate HMAC-SHA256 signature with a secret key',
    categoryId: 'crypto',
    slug: 'hmac-sha256',
    transformFn: 'generateHMACSHA256',
    isAsync: true,
    keywords: ['hmac', 'sha256', 'signature', 'mac', 'key'],
    options: [
      {
        key: 'key',
        label: 'Secret Key',
        type: 'text',
        defaultValue: '',
        placeholder: 'Enter your secret key',
      },
    ],
    inputPlaceholder: 'Enter message to sign...',
    outputPlaceholder: 'HMAC signature will appear here...',
  },
  {
    id: 'bcrypt-hash',
    name: 'Bcrypt Hash',
    description: 'Generate a bcrypt hash for password storage',
    categoryId: 'crypto',
    slug: 'bcrypt-hash',
    transformFn: 'generateBcryptHash',
    keywords: ['bcrypt', 'hash', 'password', 'secure'],
    inputPlaceholder: 'Enter password to hash...',
    outputPlaceholder: 'Bcrypt hash will appear here...',
  },
  {
    id: 'unix-to-date',
    name: 'Unix Timestamp to Date',
    description: 'Convert Unix timestamp to human-readable date',
    categoryId: 'crypto',
    slug: 'unix-to-date',
    transformFn: 'unixTimestampToDate',
    reverseFn: 'dateToUnixTimestamp',
    keywords: ['unix', 'timestamp', 'date', 'time', 'epoch'],
    inputPlaceholder: 'Enter Unix timestamp (e.g., 1609459200)...',
    outputPlaceholder: 'Date will appear here...',
  },
  {
    id: 'date-to-unix',
    name: 'Date to Unix Timestamp',
    description: 'Convert date to Unix timestamp',
    categoryId: 'crypto',
    slug: 'date-to-unix',
    transformFn: 'dateToUnixTimestamp',
    reverseFn: 'unixTimestampToDate',
    keywords: ['date', 'unix', 'timestamp', 'time', 'epoch'],
    options: [
      {
        key: 'inMilliseconds',
        label: 'Output in milliseconds',
        type: 'checkbox',
        defaultValue: false,
      },
    ],
    inputPlaceholder: 'Enter date (e.g., 2024-01-01 or 2024-01-01T00:00:00Z)...',
    outputPlaceholder: 'Unix timestamp will appear here...',
  },
  {
    id: 'generate-checksum',
    name: 'Generate CRC32 Checksum',
    description: 'Generate CRC32 checksum for data integrity verification',
    categoryId: 'crypto',
    slug: 'generate-checksum',
    transformFn: 'generateChecksum',
    keywords: ['crc32', 'checksum', 'integrity', 'hash'],
    inputPlaceholder: 'Enter text to calculate checksum...',
    outputPlaceholder: 'CRC32 checksum will appear here...',
  },
];

/**
 * Formatter Tools (18 tools)
 */
export const FORMATTER_TOOLS: Tool[] = [
  {
    id: 'format-json',
    name: 'Format JSON',
    description: 'Beautify and format JSON with proper indentation',
    categoryId: 'formatters',
    slug: 'format-json',
    transformFn: 'formatJSON',
    reverseFn: 'minifyJSON',
    keywords: ['json', 'format', 'beautify', 'pretty', 'indent'],
    options: [
      {
        key: 'indent',
        label: 'Indent Size',
        type: 'number',
        defaultValue: 2,
        min: 1,
        max: 8,
      },
    ],
    inputPlaceholder: 'Paste minified JSON here...',
  },
  {
    id: 'minify-json',
    name: 'Minify JSON',
    description: 'Remove whitespace and compress JSON',
    categoryId: 'formatters',
    slug: 'minify-json',
    transformFn: 'minifyJSON',
    reverseFn: 'formatJSON',
    keywords: ['json', 'minify', 'compress', 'compact'],
    inputPlaceholder: 'Paste formatted JSON here...',
  },
  {
    id: 'format-sql',
    name: 'Format SQL',
    description: 'Beautify and format SQL queries with proper indentation',
    categoryId: 'formatters',
    slug: 'format-sql',
    transformFn: 'formatSQL',
    reverseFn: 'minifySQL',
    keywords: ['sql', 'format', 'beautify', 'query', 'database'],
    inputPlaceholder: 'Paste SQL query here...',
  },
  {
    id: 'minify-sql',
    name: 'Minify SQL',
    description: 'Compress SQL query to single line',
    categoryId: 'formatters',
    slug: 'minify-sql',
    transformFn: 'minifySQL',
    reverseFn: 'formatSQL',
    keywords: ['sql', 'minify', 'compress', 'query'],
    inputPlaceholder: 'Paste formatted SQL here...',
  },
  {
    id: 'format-xml',
    name: 'Format XML',
    description: 'Beautify and format XML with proper indentation',
    categoryId: 'formatters',
    slug: 'format-xml',
    transformFn: 'formatXML',
    reverseFn: 'minifyXML',
    keywords: ['xml', 'format', 'beautify', 'pretty'],
    inputPlaceholder: 'Paste minified XML here...',
  },
  {
    id: 'minify-xml',
    name: 'Minify XML',
    description: 'Remove whitespace and compress XML',
    categoryId: 'formatters',
    slug: 'minify-xml',
    transformFn: 'minifyXML',
    reverseFn: 'formatXML',
    keywords: ['xml', 'minify', 'compress', 'compact'],
    inputPlaceholder: 'Paste formatted XML here...',
  },
  {
    id: 'format-css',
    name: 'Format CSS',
    description: 'Beautify and format CSS with proper indentation',
    categoryId: 'formatters',
    slug: 'format-css',
    transformFn: 'formatCSS',
    reverseFn: 'minifyCSS',
    keywords: ['css', 'format', 'beautify', 'pretty', 'styles'],
    inputPlaceholder: 'Paste minified CSS here...',
  },
  {
    id: 'minify-css',
    name: 'Minify CSS',
    description: 'Remove whitespace and compress CSS',
    categoryId: 'formatters',
    slug: 'minify-css',
    transformFn: 'minifyCSS',
    reverseFn: 'formatCSS',
    keywords: ['css', 'minify', 'compress', 'compact', 'styles'],
    inputPlaceholder: 'Paste formatted CSS here...',
  },
  {
    id: 'format-javascript',
    name: 'Format JavaScript',
    description: 'Beautify and format JavaScript code',
    categoryId: 'formatters',
    slug: 'format-javascript',
    transformFn: 'formatJavaScript',
    reverseFn: 'minifyJavaScript',
    keywords: ['javascript', 'js', 'format', 'beautify', 'code'],
    inputPlaceholder: 'Paste minified JavaScript here...',
  },
  {
    id: 'minify-javascript',
    name: 'Minify JavaScript',
    description: 'Remove whitespace and compress JavaScript',
    categoryId: 'formatters',
    slug: 'minify-javascript',
    transformFn: 'minifyJavaScript',
    reverseFn: 'formatJavaScript',
    keywords: ['javascript', 'js', 'minify', 'compress', 'code'],
    inputPlaceholder: 'Paste formatted JavaScript here...',
  },
  {
    id: 'format-html',
    name: 'Format HTML',
    description: 'Beautify and format HTML with proper indentation',
    categoryId: 'formatters',
    slug: 'format-html',
    transformFn: 'formatHTML',
    reverseFn: 'minifyHTML',
    keywords: ['html', 'format', 'beautify', 'pretty', 'markup'],
    inputPlaceholder: 'Paste minified HTML here...',
  },
  {
    id: 'minify-html',
    name: 'Minify HTML',
    description: 'Remove whitespace and compress HTML',
    categoryId: 'formatters',
    slug: 'minify-html',
    transformFn: 'minifyHTML',
    reverseFn: 'formatHTML',
    keywords: ['html', 'minify', 'compress', 'compact', 'markup'],
    inputPlaceholder: 'Paste formatted HTML here...',
  },
  {
    id: 'format-yaml',
    name: 'Format YAML',
    description: 'Beautify and validate YAML syntax',
    categoryId: 'formatters',
    slug: 'format-yaml',
    transformFn: 'formatYAML',
    keywords: ['yaml', 'yml', 'format', 'beautify', 'config'],
    inputPlaceholder: 'Paste YAML here...',
  },
  {
    id: 'json-to-yaml',
    name: 'JSON to YAML',
    description: 'Convert JSON data to YAML format',
    categoryId: 'formatters',
    slug: 'json-to-yaml',
    transformFn: 'jsonToYAML',
    reverseFn: 'yamlToJSON',
    keywords: ['json', 'yaml', 'convert', 'transform'],
    inputPlaceholder: 'Paste JSON here...',
    outputPlaceholder: 'YAML will appear here...',
  },
  {
    id: 'yaml-to-json',
    name: 'YAML to JSON',
    description: 'Convert YAML data to JSON format',
    categoryId: 'formatters',
    slug: 'yaml-to-json',
    transformFn: 'yamlToJSON',
    reverseFn: 'jsonToYAML',
    keywords: ['yaml', 'json', 'convert', 'transform'],
    inputPlaceholder: 'Paste YAML here...',
    outputPlaceholder: 'JSON will appear here...',
  },
  {
    id: 'markdown-to-html',
    name: 'Markdown to HTML',
    description: 'Convert Markdown text to HTML',
    categoryId: 'formatters',
    slug: 'markdown-to-html',
    transformFn: 'markdownToHTML',
    reverseFn: 'htmlToMarkdown',
    keywords: ['markdown', 'md', 'html', 'convert'],
    inputPlaceholder: 'Paste Markdown here...',
    outputPlaceholder: 'HTML will appear here...',
  },
  {
    id: 'html-to-markdown',
    name: 'HTML to Markdown',
    description: 'Convert HTML to Markdown format',
    categoryId: 'formatters',
    slug: 'html-to-markdown',
    transformFn: 'htmlToMarkdown',
    reverseFn: 'markdownToHTML',
    keywords: ['html', 'markdown', 'md', 'convert'],
    inputPlaceholder: 'Paste HTML here...',
    outputPlaceholder: 'Markdown will appear here...',
  },
  {
    id: 'curl-to-code',
    name: 'cURL to Code',
    description: 'Convert cURL commands to JavaScript, Python, or PHP code',
    categoryId: 'formatters',
    slug: 'curl-to-code',
    transformFn: 'curlToCode',
    keywords: ['curl', 'convert', 'javascript', 'python', 'php', 'http'],
    options: [
      {
        key: 'language',
        label: 'Target Language',
        type: 'select',
        defaultValue: 'javascript',
        options: [
          { label: 'JavaScript (fetch)', value: 'javascript' },
          { label: 'Python (requests)', value: 'python' },
          { label: 'PHP (cURL)', value: 'php' },
        ],
      },
    ],
    inputPlaceholder: 'Paste cURL command here...',
    outputPlaceholder: 'Generated code will appear here...',
  },
];

/**
 * All Batch 1 tools combined
 */
export const BATCH1_TOOLS: Tool[] = [
  ...NAMING_CONVENTION_TOOLS,
  ...ENCODING_TOOLS,
  ...CRYPTO_TOOLS,
  ...FORMATTER_TOOLS,
];

/**
 * Batch 1 tool count
 */
export const BATCH1_TOOL_COUNT = BATCH1_TOOLS.length;
