/**
 * Tool Definitions - Batch 2
 * Categories: converters, colors, generators, ciphers
 * Total: 52 tools
 */

import type { Tool } from '../types';

/**
 * Converter Tools (7 tools)
 * Note: markdownToHTML, htmlToMarkdown, curlToCode are in converters.ts
 * but logically grouped with formatters for UX
 */
export const CONVERTER_TOOLS: Tool[] = [
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    description: 'Convert CSV data to JSON array format',
    categoryId: 'converters',
    slug: 'csv-to-json',
    transformFn: 'csvToJSON',
    reverseFn: 'jsonToCSV',
    keywords: ['csv', 'json', 'convert', 'data', 'array'],
    options: [
      {
        key: 'hasHeader',
        label: 'First row is header',
        type: 'checkbox',
        defaultValue: true,
      },
    ],
    inputPlaceholder: 'Paste CSV data here...',
    outputPlaceholder: 'JSON array will appear here...',
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV',
    description: 'Convert JSON array to CSV format',
    categoryId: 'converters',
    slug: 'json-to-csv',
    transformFn: 'jsonToCSV',
    reverseFn: 'csvToJSON',
    keywords: ['json', 'csv', 'convert', 'data', 'export'],
    inputPlaceholder: 'Paste JSON array here...',
    outputPlaceholder: 'CSV data will appear here...',
  },
  {
    id: 'xml-to-json',
    name: 'XML to JSON',
    description: 'Convert XML data to JSON format',
    categoryId: 'converters',
    slug: 'xml-to-json',
    transformFn: 'xmlToJSON',
    reverseFn: 'jsonToXML',
    keywords: ['xml', 'json', 'convert', 'data', 'api'],
    inputPlaceholder: 'Paste XML data here...',
    outputPlaceholder: 'JSON will appear here...',
  },
  {
    id: 'json-to-xml',
    name: 'JSON to XML',
    description: 'Convert JSON data to XML format',
    categoryId: 'converters',
    slug: 'json-to-xml',
    transformFn: 'jsonToXML',
    reverseFn: 'xmlToJSON',
    keywords: ['json', 'xml', 'convert', 'data', 'api'],
    inputPlaceholder: 'Paste JSON data here...',
    outputPlaceholder: 'XML will appear here...',
  },
];

/**
 * Color Tools (12 tools)
 */
export const COLOR_TOOLS: Tool[] = [
  {
    id: 'hex-to-rgb',
    name: 'HEX to RGB',
    description: 'Convert HEX color code to RGB format',
    categoryId: 'colors',
    slug: 'hex-to-rgb',
    transformFn: 'hexToRgb',
    reverseFn: 'rgbToHex',
    keywords: ['hex', 'rgb', 'color', 'convert', 'css'],
    inputPlaceholder: 'Enter HEX color (e.g., #FF5733 or FF5733)...',
    outputPlaceholder: 'RGB value will appear here...',
  },
  {
    id: 'rgb-to-hex',
    name: 'RGB to HEX',
    description: 'Convert RGB color values to HEX format',
    categoryId: 'colors',
    slug: 'rgb-to-hex',
    transformFn: 'rgbToHex',
    reverseFn: 'hexToRgb',
    keywords: ['rgb', 'hex', 'color', 'convert', 'css'],
    inputPlaceholder: 'Enter RGB (e.g., rgb(255, 87, 51) or 255,87,51)...',
    outputPlaceholder: 'HEX value will appear here...',
  },
  {
    id: 'hex-to-hsl',
    name: 'HEX to HSL',
    description: 'Convert HEX color code to HSL format',
    categoryId: 'colors',
    slug: 'hex-to-hsl',
    transformFn: 'hexToHsl',
    reverseFn: 'hslToHex',
    keywords: ['hex', 'hsl', 'color', 'convert', 'css'],
    inputPlaceholder: 'Enter HEX color (e.g., #FF5733)...',
    outputPlaceholder: 'HSL value will appear here...',
  },
  {
    id: 'hsl-to-hex',
    name: 'HSL to HEX',
    description: 'Convert HSL color values to HEX format',
    categoryId: 'colors',
    slug: 'hsl-to-hex',
    transformFn: 'hslToHex',
    reverseFn: 'hexToHsl',
    keywords: ['hsl', 'hex', 'color', 'convert', 'css'],
    inputPlaceholder: 'Enter HSL (e.g., hsl(11, 100%, 60%))...',
    outputPlaceholder: 'HEX value will appear here...',
  },
  {
    id: 'decimal-to-hex-color',
    name: 'Decimal to HEX',
    description: 'Convert decimal color value to HEX format',
    categoryId: 'colors',
    slug: 'decimal-to-hex',
    transformFn: 'decimalToHex',
    reverseFn: 'hexToDecimal',
    keywords: ['decimal', 'hex', 'color', 'convert', 'number'],
    inputPlaceholder: 'Enter decimal value (e.g., 16711680)...',
    outputPlaceholder: 'HEX value will appear here...',
  },
  {
    id: 'hex-to-decimal-color',
    name: 'HEX to Decimal',
    description: 'Convert HEX color code to decimal number',
    categoryId: 'colors',
    slug: 'hex-to-decimal',
    transformFn: 'hexToDecimal',
    reverseFn: 'decimalToHex',
    keywords: ['hex', 'decimal', 'color', 'convert', 'number'],
    inputPlaceholder: 'Enter HEX color (e.g., FF0000)...',
    outputPlaceholder: 'Decimal value will appear here...',
  },
  {
    id: 'hex-to-rgba',
    name: 'HEX to RGBA',
    description: 'Convert HEX color to RGBA with alpha transparency',
    categoryId: 'colors',
    slug: 'hex-to-rgba',
    transformFn: 'hexToRgba',
    keywords: ['hex', 'rgba', 'color', 'alpha', 'transparency'],
    options: [
      {
        key: 'alpha',
        label: 'Alpha (0-1)',
        type: 'number',
        defaultValue: 1,
        min: 0,
        max: 1,
      },
    ],
    inputPlaceholder: 'Enter HEX color (e.g., #FF5733)...',
    outputPlaceholder: 'RGBA value will appear here...',
  },
  {
    id: 'random-hex-color',
    name: 'Random HEX Color',
    description: 'Generate random HEX color codes',
    categoryId: 'colors',
    slug: 'random-hex-color',
    transformFn: 'generateRandomHexColor',
    isGenerator: true,
    keywords: ['random', 'hex', 'color', 'generate'],
    options: [
      {
        key: 'count',
        label: 'How Many',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
    ],
    inputPlaceholder: 'Click Generate to create random colors...',
    outputPlaceholder: 'Random HEX colors will appear here...',
  },
  {
    id: 'complementary-color',
    name: 'Complementary Color',
    description: 'Find the complementary (opposite) color',
    categoryId: 'colors',
    slug: 'complementary-color',
    transformFn: 'getComplementaryColor',
    keywords: ['complementary', 'opposite', 'color', 'design'],
    inputPlaceholder: 'Enter HEX color (e.g., #FF5733)...',
    outputPlaceholder: 'Complementary color will appear here...',
  },
  {
    id: 'hex-to-css-variable',
    name: 'HEX to CSS Variable',
    description: 'Convert HEX color to CSS custom property format',
    categoryId: 'colors',
    slug: 'hex-to-css-variable',
    transformFn: 'hexToCssVariable',
    keywords: ['hex', 'css', 'variable', 'custom', 'property'],
    options: [
      {
        key: 'variableName',
        label: 'Variable Name',
        type: 'text',
        defaultValue: 'color-primary',
        placeholder: 'e.g., color-primary',
      },
    ],
    inputPlaceholder: 'Enter HEX color (e.g., #FF5733)...',
    outputPlaceholder: 'CSS variable will appear here...',
  },
  {
    id: 'parse-color',
    name: 'Parse Color',
    description: 'Parse any color format and show all conversions',
    categoryId: 'colors',
    slug: 'parse-color',
    transformFn: 'parseColor',
    keywords: ['parse', 'color', 'analyze', 'all', 'formats'],
    inputPlaceholder: 'Enter color in any format (HEX, RGB, HSL)...',
    outputPlaceholder: 'All color formats will appear here...',
  },
];

/**
 * Generator Tools (13 tools)
 */
export const GENERATOR_TOOLS: Tool[] = [
  {
    id: 'generate-password',
    name: 'Password Generator',
    description: 'Generate secure random passwords with custom options',
    categoryId: 'generators',
    slug: 'password-generator',
    transformFn: 'generatePassword',
    isGenerator: true,
    keywords: ['password', 'generate', 'random', 'secure', 'strong'],
    options: [
      {
        key: 'count',
        label: 'How Many',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
      {
        key: 'length',
        label: 'Length',
        type: 'number',
        defaultValue: 16,
        min: 4,
        max: 128,
      },
      {
        key: 'includeUppercase',
        label: 'Uppercase',
        type: 'checkbox',
        defaultValue: true,
      },
      {
        key: 'includeLowercase',
        label: 'Lowercase',
        type: 'checkbox',
        defaultValue: true,
      },
      {
        key: 'includeNumbers',
        label: 'Numbers',
        type: 'checkbox',
        defaultValue: true,
      },
      {
        key: 'includeSymbols',
        label: 'Symbols',
        type: 'checkbox',
        defaultValue: true,
      },
    ],
    inputPlaceholder: 'Click Generate to create passwords...',
    outputPlaceholder: 'Generated passwords will appear here...',
  },
  {
    id: 'generate-ipv4',
    name: 'Random IPv4 Address',
    description: 'Generate random IPv4 addresses',
    categoryId: 'generators',
    slug: 'random-ipv4',
    transformFn: 'generateIPv4',
    isGenerator: true,
    keywords: ['ip', 'ipv4', 'address', 'network', 'random'],
    options: [
      {
        key: 'count',
        label: 'How Many',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
    ],
    inputPlaceholder: 'Click Generate to create IPv4 addresses...',
    outputPlaceholder: 'IPv4 addresses will appear here...',
  },
  {
    id: 'generate-ipv6',
    name: 'Random IPv6 Address',
    description: 'Generate random IPv6 addresses',
    categoryId: 'generators',
    slug: 'random-ipv6',
    transformFn: 'generateIPv6',
    isGenerator: true,
    keywords: ['ip', 'ipv6', 'address', 'network', 'random'],
    options: [
      {
        key: 'count',
        label: 'How Many',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
    ],
    inputPlaceholder: 'Click Generate to create IPv6 addresses...',
    outputPlaceholder: 'IPv6 addresses will appear here...',
  },
  {
    id: 'generate-mac-address',
    name: 'Random MAC Address',
    description: 'Generate random MAC addresses',
    categoryId: 'generators',
    slug: 'random-mac-address',
    transformFn: 'generateMacAddress',
    isGenerator: true,
    keywords: ['mac', 'address', 'network', 'hardware', 'random'],
    options: [
      {
        key: 'count',
        label: 'How Many',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
      {
        key: 'separator',
        label: 'Separator',
        type: 'select',
        defaultValue: ':',
        options: [
          { label: 'Colon (:)', value: ':' },
          { label: 'Hyphen (-)', value: '-' },
          { label: 'None', value: '' },
        ],
      },
    ],
    inputPlaceholder: 'Click Generate to create MAC addresses...',
    outputPlaceholder: 'MAC addresses will appear here...',
  },
  {
    id: 'generate-random-string',
    name: 'Random String Generator',
    description: 'Generate random strings with custom character sets',
    categoryId: 'generators',
    slug: 'random-string',
    transformFn: 'generateRandomString',
    isGenerator: true,
    keywords: ['random', 'string', 'generate', 'characters'],
    options: [
      {
        key: 'count',
        label: 'How Many',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
      {
        key: 'length',
        label: 'Length',
        type: 'number',
        defaultValue: 16,
        min: 1,
        max: 256,
      },
      {
        key: 'charset',
        label: 'Character Set',
        type: 'select',
        defaultValue: 'alphanumeric',
        options: [
          { label: 'Alphanumeric', value: 'alphanumeric' },
          { label: 'Alphabetic', value: 'alpha' },
          { label: 'Numeric', value: 'numeric' },
          { label: 'Hexadecimal', value: 'hex' },
        ],
      },
    ],
    inputPlaceholder: 'Click Generate to create random strings...',
    outputPlaceholder: 'Random strings will appear here...',
  },
  {
    id: 'generate-lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate Lorem Ipsum placeholder text',
    categoryId: 'generators',
    slug: 'lorem-ipsum',
    transformFn: 'generateLoremIpsum',
    isGenerator: true,
    keywords: ['lorem', 'ipsum', 'placeholder', 'text', 'dummy'],
    options: [
      {
        key: 'paragraphs',
        label: 'Paragraphs',
        type: 'number',
        defaultValue: 3,
        min: 1,
        max: 20,
      },
      {
        key: 'wordsPerParagraph',
        label: 'Words per Paragraph',
        type: 'number',
        defaultValue: 50,
        min: 10,
        max: 200,
      },
    ],
    inputPlaceholder: 'Click Generate to create Lorem Ipsum text...',
    outputPlaceholder: 'Lorem Ipsum text will appear here...',
  },
  {
    id: 'generate-random-date',
    name: 'Random Date Generator',
    description: 'Generate random dates within a range',
    categoryId: 'generators',
    slug: 'random-date',
    transformFn: 'generateRandomDate',
    isGenerator: true,
    keywords: ['date', 'random', 'generate', 'time'],
    options: [
      {
        key: 'count',
        label: 'How Many',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
    ],
    inputPlaceholder: 'Click Generate to create random dates...',
    outputPlaceholder: 'Random dates will appear here...',
  },
  {
    id: 'generate-random-email',
    name: 'Random Email Generator',
    description: 'Generate realistic random email addresses',
    categoryId: 'generators',
    slug: 'random-email',
    transformFn: 'generateRandomEmail',
    isGenerator: true,
    keywords: ['email', 'random', 'generate', 'test', 'fake'],
    options: [
      {
        key: 'count',
        label: 'How Many',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
      {
        key: 'domain',
        label: 'Domain',
        type: 'text',
        defaultValue: 'example.com',
        placeholder: 'e.g., example.com',
      },
    ],
    inputPlaceholder: 'Click Generate to create random emails...',
    outputPlaceholder: 'Random emails will appear here...',
  },
  {
    id: 'generate-random-username',
    name: 'Random Username Generator',
    description: 'Generate creative random usernames',
    categoryId: 'generators',
    slug: 'random-username',
    transformFn: 'generateRandomUsername',
    isGenerator: true,
    keywords: ['username', 'random', 'generate', 'user', 'name'],
    options: [
      {
        key: 'count',
        label: 'How Many',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
    ],
    inputPlaceholder: 'Click Generate to create random usernames...',
    outputPlaceholder: 'Random usernames will appear here...',
  },
  {
    id: 'generate-random-phone',
    name: 'Random Phone Number',
    description: 'Generate random phone numbers in various formats',
    categoryId: 'generators',
    slug: 'random-phone',
    transformFn: 'generateRandomPhone',
    isGenerator: true,
    keywords: ['phone', 'number', 'random', 'generate', 'tel'],
    options: [
      {
        key: 'count',
        label: 'How Many',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
      {
        key: 'format',
        label: 'Format',
        type: 'select',
        defaultValue: 'us',
        options: [
          { label: 'US Format', value: 'us' },
          { label: 'International', value: 'international' },
        ],
      },
    ],
    inputPlaceholder: 'Click Generate to create phone numbers...',
    outputPlaceholder: 'Random phone numbers will appear here...',
  },
  {
    id: 'generate-test-credit-card',
    name: 'Test Credit Card Generator',
    description: 'Generate valid test credit card numbers (Luhn valid)',
    categoryId: 'generators',
    slug: 'test-credit-card',
    transformFn: 'generateTestCreditCard',
    isGenerator: true,
    keywords: ['credit', 'card', 'test', 'luhn', 'payment', 'visa', 'mastercard'],
    options: [
      {
        key: 'count',
        label: 'How Many',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
      {
        key: 'type',
        label: 'Card Type',
        type: 'select',
        defaultValue: 'visa',
        options: [
          { label: 'Visa', value: 'visa' },
          { label: 'Mastercard', value: 'mastercard' },
          { label: 'American Express', value: 'amex' },
        ],
      },
    ],
    inputPlaceholder: 'Click Generate to create test card numbers...',
    outputPlaceholder: 'Test credit card numbers will appear here...',
  },
  {
    id: 'generate-slug',
    name: 'Random Slug Generator',
    description: 'Generate URL-friendly random slugs',
    categoryId: 'generators',
    slug: 'random-slug',
    transformFn: 'generateSlug',
    isGenerator: true,
    keywords: ['slug', 'url', 'random', 'generate', 'seo'],
    options: [
      {
        key: 'count',
        label: 'How Many',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
      {
        key: 'words',
        label: 'Words per Slug',
        type: 'number',
        defaultValue: 3,
        min: 1,
        max: 10,
      },
    ],
    inputPlaceholder: 'Click Generate to create random slugs...',
    outputPlaceholder: 'Random slugs will appear here...',
  },
  {
    id: 'generate-api-key',
    name: 'API Key Generator',
    description: 'Generate secure API keys with custom prefixes',
    categoryId: 'generators',
    slug: 'api-key-generator',
    transformFn: 'generateApiKey',
    isGenerator: true,
    keywords: ['api', 'key', 'token', 'generate', 'secret'],
    options: [
      {
        key: 'count',
        label: 'How Many',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
      {
        key: 'prefix',
        label: 'Prefix',
        type: 'text',
        defaultValue: 'sk',
        placeholder: 'e.g., sk, pk, api',
      },
    ],
    inputPlaceholder: 'Click Transform to generate API keys...',
    outputPlaceholder: 'API keys will appear here...',
  },
  {
    id: 'generate-random-integers',
    name: 'Random Integer Generator',
    description: 'Generate random integers within a specified range',
    categoryId: 'generators',
    slug: 'random-integers',
    transformFn: 'generateRandomIntegers',
    isGenerator: true,
    keywords: ['random', 'integer', 'number', 'range', 'generate'],
    options: [
      {
        key: 'min',
        label: 'Minimum',
        type: 'number',
        defaultValue: 1,
      },
      {
        key: 'max',
        label: 'Maximum',
        type: 'number',
        defaultValue: 100,
      },
      {
        key: 'count',
        label: 'How Many',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
      {
        key: 'unique',
        label: 'Unique Numbers Only',
        type: 'checkbox',
        defaultValue: false,
      },
    ],
    inputPlaceholder: 'Click Transform to generate random integers...',
    outputPlaceholder: 'Random integers will appear here...',
  },
  {
    id: 'roll-dice',
    name: 'Dice Roller',
    description: 'Roll dice with configurable sides (D4, D6, D8, D10, D12, D20, D100)',
    categoryId: 'generators',
    slug: 'dice-roller',
    transformFn: 'rollDice',
    isGenerator: true,
    keywords: ['dice', 'roll', 'random', 'd20', 'd6', 'rpg', 'game'],
    options: [
      {
        key: 'sides',
        label: 'Dice Type',
        type: 'select',
        defaultValue: '6',
        options: [
          { label: 'D4 (4 sides)', value: '4' },
          { label: 'D6 (6 sides)', value: '6' },
          { label: 'D8 (8 sides)', value: '8' },
          { label: 'D10 (10 sides)', value: '10' },
          { label: 'D12 (12 sides)', value: '12' },
          { label: 'D20 (20 sides)', value: '20' },
          { label: 'D100 (100 sides)', value: '100' },
        ],
      },
      {
        key: 'count',
        label: 'Number of Dice',
        type: 'number',
        defaultValue: 1,
        min: 1,
        max: 20,
      },
      {
        key: 'showTotal',
        label: 'Show Total',
        type: 'checkbox',
        defaultValue: true,
      },
    ],
    inputPlaceholder: 'Click Transform to roll dice...',
    outputPlaceholder: 'Dice roll results will appear here...',
  },
  {
    id: 'flip-coins',
    name: 'Coin Flipper',
    description: 'Flip coins and get heads or tails results',
    categoryId: 'generators',
    slug: 'coin-flipper',
    transformFn: 'flipCoins',
    isGenerator: true,
    keywords: ['coin', 'flip', 'heads', 'tails', 'random', 'chance'],
    options: [
      {
        key: 'count',
        label: 'Number of Flips',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
    ],
    inputPlaceholder: 'Click Transform to flip coins...',
    outputPlaceholder: 'Coin flip results will appear here...',
  },
  {
    id: 'generate-random-time',
    name: 'Random Time Generator',
    description: 'Generate random times of day',
    categoryId: 'generators',
    slug: 'random-time',
    transformFn: 'generateRandomTime',
    isGenerator: true,
    keywords: ['time', 'clock', 'random', 'generate', 'hour'],
    options: [
      {
        key: 'count',
        label: 'How Many',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
      {
        key: 'format',
        label: 'Time Format',
        type: 'select',
        defaultValue: '24h',
        options: [
          { label: '24-hour (14:30:00)', value: '24h' },
          { label: '12-hour (2:30:00 PM)', value: '12h' },
        ],
      },
    ],
    inputPlaceholder: 'Click Transform to generate random times...',
    outputPlaceholder: 'Random times will appear here...',
  },
  {
    id: 'shuffle-sequence',
    name: 'Sequence Shuffler',
    description: 'Shuffle a sequence of numbers in random order',
    categoryId: 'generators',
    slug: 'sequence-shuffler',
    transformFn: 'shuffleSequence',
    isGenerator: true,
    keywords: ['shuffle', 'sequence', 'random', 'order', 'permutation'],
    options: [
      {
        key: 'start',
        label: 'Start Number',
        type: 'number',
        defaultValue: 1,
      },
      {
        key: 'end',
        label: 'End Number',
        type: 'number',
        defaultValue: 10,
      },
    ],
    inputPlaceholder: 'Click Transform to shuffle a sequence...',
    outputPlaceholder: 'Shuffled sequence will appear here...',
  },
  {
    id: 'generate-random-decimals',
    name: 'Random Decimal Generator',
    description: 'Generate random decimal numbers between 0 and 1',
    categoryId: 'generators',
    slug: 'random-decimals',
    transformFn: 'generateRandomDecimals',
    isGenerator: true,
    keywords: ['decimal', 'fraction', 'random', 'float', 'number'],
    options: [
      {
        key: 'count',
        label: 'How Many',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
      {
        key: 'decimalPlaces',
        label: 'Decimal Places',
        type: 'number',
        defaultValue: 2,
        min: 1,
        max: 10,
      },
    ],
    inputPlaceholder: 'Click Transform to generate random decimals...',
    outputPlaceholder: 'Random decimals will appear here...',
  },
  {
    id: 'generate-hex-colors',
    name: 'Random Color Generator',
    description: 'Generate multiple random HEX color codes',
    categoryId: 'generators',
    slug: 'random-colors',
    transformFn: 'generateHexColors',
    isGenerator: true,
    keywords: ['color', 'hex', 'random', 'palette', 'design'],
    options: [
      {
        key: 'count',
        label: 'How Many Colors',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
    ],
    inputPlaceholder: 'Click Transform to generate random colors...',
    outputPlaceholder: 'Random HEX colors will appear here...',
  },
  {
    id: 'generate-random-bytes',
    name: 'Random Bytes Generator',
    description: 'Generate cryptographically secure random bytes (hex encoded)',
    categoryId: 'generators',
    slug: 'random-bytes',
    transformFn: 'generateRandomBytes',
    isGenerator: true,
    keywords: ['bytes', 'random', 'hex', 'crypto', 'secure'],
    options: [
      {
        key: 'count',
        label: 'Number of Bytes',
        type: 'number',
        defaultValue: 16,
        min: 1,
        max: 256,
      },
    ],
    inputPlaceholder: 'Click Transform to generate random bytes...',
    outputPlaceholder: 'Random bytes (hex) will appear here...',
  },
  {
    id: 'pick-from-list',
    name: 'List Picker',
    description: 'Randomly pick items from a list (one per line)',
    categoryId: 'generators',
    slug: 'list-picker',
    transformFn: 'pickFromList',
    isGenerator: false,
    keywords: ['pick', 'random', 'list', 'select', 'choose', 'lottery'],
    options: [
      {
        key: 'count',
        label: 'How Many to Pick',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
      },
      {
        key: 'unique',
        label: 'No Duplicates',
        type: 'checkbox',
        defaultValue: true,
      },
    ],
    inputPlaceholder: 'Enter items (one per line)...',
    outputPlaceholder: 'Randomly picked items will appear here...',
  },
];

/**
 * Cipher Tools (15 tools)
 */
export const CIPHER_TOOLS: Tool[] = [
  {
    id: 'caesar-encode',
    name: 'Caesar Cipher Encode',
    description: 'Encode text using the Caesar cipher with configurable shift',
    categoryId: 'ciphers',
    slug: 'caesar-encode',
    transformFn: 'caesarEncode',
    reverseFn: 'caesarDecode',
    keywords: ['caesar', 'cipher', 'encode', 'shift', 'classic'],
    options: [
      {
        key: 'shift',
        label: 'Shift Amount',
        type: 'number',
        defaultValue: 3,
        min: 1,
        max: 25,
      },
    ],
    inputPlaceholder: 'Enter text to encode...',
  },
  {
    id: 'caesar-decode',
    name: 'Caesar Cipher Decode',
    description: 'Decode text encoded with Caesar cipher',
    categoryId: 'ciphers',
    slug: 'caesar-decode',
    transformFn: 'caesarDecode',
    reverseFn: 'caesarEncode',
    keywords: ['caesar', 'cipher', 'decode', 'shift', 'classic'],
    options: [
      {
        key: 'shift',
        label: 'Shift Amount',
        type: 'number',
        defaultValue: 3,
        min: 1,
        max: 25,
      },
    ],
    inputPlaceholder: 'Enter Caesar cipher text to decode...',
  },
  {
    id: 'rot13',
    name: 'ROT13',
    description: 'Apply ROT13 cipher (self-reversing with shift of 13)',
    categoryId: 'ciphers',
    slug: 'rot13',
    transformFn: 'rot13',
    keywords: ['rot13', 'cipher', 'caesar', 'classic', 'reversible'],
    inputPlaceholder: 'Enter text to ROT13 encode/decode...',
  },
  {
    id: 'rot47',
    name: 'ROT47',
    description: 'Apply ROT47 cipher (extends ROT13 to ASCII printable)',
    categoryId: 'ciphers',
    slug: 'rot47',
    transformFn: 'rot47',
    keywords: ['rot47', 'cipher', 'ascii', 'classic', 'reversible'],
    inputPlaceholder: 'Enter text to ROT47 encode/decode...',
  },
  {
    id: 'atbash',
    name: 'Atbash Cipher',
    description: 'Apply Atbash cipher (reverse alphabet substitution)',
    categoryId: 'ciphers',
    slug: 'atbash',
    transformFn: 'atbash',
    keywords: ['atbash', 'cipher', 'hebrew', 'classic', 'reversible'],
    inputPlaceholder: 'Enter text to apply Atbash cipher...',
  },
  {
    id: 'text-to-morse',
    name: 'Text to Morse Code',
    description: 'Convert text to Morse code (dots and dashes)',
    categoryId: 'ciphers',
    slug: 'text-to-morse',
    transformFn: 'textToMorse',
    reverseFn: 'morseToText',
    keywords: ['morse', 'code', 'encode', 'dots', 'dashes', 'telegraph'],
    inputPlaceholder: 'Enter text to convert to Morse code...',
  },
  {
    id: 'morse-to-text',
    name: 'Morse Code to Text',
    description: 'Convert Morse code back to text',
    categoryId: 'ciphers',
    slug: 'morse-to-text',
    transformFn: 'morseToText',
    reverseFn: 'textToMorse',
    keywords: ['morse', 'code', 'decode', 'text', 'telegraph'],
    inputPlaceholder: 'Enter Morse code (e.g., .... . .-.. .-.. ---)...',
  },
  {
    id: 'vigenere-encode',
    name: 'Vigenère Cipher Encode',
    description: 'Encode text using the Vigenère cipher with a keyword',
    categoryId: 'ciphers',
    slug: 'vigenere-encode',
    transformFn: 'vigenereEncode',
    reverseFn: 'vigenereDecode',
    keywords: ['vigenere', 'cipher', 'encode', 'key', 'polyalphabetic'],
    options: [
      {
        key: 'key',
        label: 'Keyword',
        type: 'text',
        defaultValue: 'SECRET',
        placeholder: 'Enter encryption key',
      },
    ],
    inputPlaceholder: 'Enter text to encode...',
  },
  {
    id: 'vigenere-decode',
    name: 'Vigenère Cipher Decode',
    description: 'Decode text encoded with Vigenère cipher',
    categoryId: 'ciphers',
    slug: 'vigenere-decode',
    transformFn: 'vigenereDecode',
    reverseFn: 'vigenereEncode',
    keywords: ['vigenere', 'cipher', 'decode', 'key', 'polyalphabetic'],
    options: [
      {
        key: 'key',
        label: 'Keyword',
        type: 'text',
        defaultValue: 'SECRET',
        placeholder: 'Enter decryption key',
      },
    ],
    inputPlaceholder: 'Enter Vigenère cipher text to decode...',
  },
  {
    id: 'text-to-nato',
    name: 'NATO Phonetic Alphabet',
    description: 'Convert text to NATO phonetic alphabet',
    categoryId: 'ciphers',
    slug: 'text-to-nato',
    transformFn: 'textToNato',
    keywords: ['nato', 'phonetic', 'alphabet', 'military', 'spelling'],
    inputPlaceholder: 'Enter text to convert to NATO alphabet...',
  },
  {
    id: 'to-pig-latin',
    name: 'Pig Latin',
    description: 'Convert text to Pig Latin',
    categoryId: 'ciphers',
    slug: 'pig-latin',
    transformFn: 'toPigLatin',
    keywords: ['pig', 'latin', 'fun', 'word', 'game'],
    inputPlaceholder: 'Enter text to convert to Pig Latin...',
  },
  {
    id: 'reverse-words',
    name: 'Reverse Words',
    description: 'Reverse the order of words in text',
    categoryId: 'ciphers',
    slug: 'reverse-words',
    transformFn: 'reverseWords',
    keywords: ['reverse', 'words', 'order', 'flip'],
    inputPlaceholder: 'Enter text to reverse word order...',
  },
  {
    id: 'reverse-string',
    name: 'Reverse String',
    description: 'Reverse the entire string character by character',
    categoryId: 'ciphers',
    slug: 'reverse-string',
    transformFn: 'reverseString',
    keywords: ['reverse', 'string', 'characters', 'backwards'],
    inputPlaceholder: 'Enter text to reverse...',
  },
  {
    id: 'xor-cipher',
    name: 'XOR Cipher',
    description: 'Apply XOR cipher with a key (self-reversing)',
    categoryId: 'ciphers',
    slug: 'xor-cipher',
    transformFn: 'xorCipher',
    keywords: ['xor', 'cipher', 'bitwise', 'key', 'reversible'],
    options: [
      {
        key: 'key',
        label: 'XOR Key',
        type: 'text',
        defaultValue: 'KEY',
        placeholder: 'Enter XOR key',
      },
    ],
    inputPlaceholder: 'Enter text to XOR encode/decode...',
  },
  {
    id: 'substitution-cipher',
    name: 'Substitution Cipher',
    description: 'Apply substitution cipher with custom alphabet',
    categoryId: 'ciphers',
    slug: 'substitution-cipher',
    transformFn: 'substitutionCipher',
    keywords: ['substitution', 'cipher', 'alphabet', 'custom'],
    options: [
      {
        key: 'alphabet',
        label: 'Substitution Alphabet',
        type: 'text',
        defaultValue: 'QWERTYUIOPASDFGHJKLZXCVBNM',
        placeholder: '26 unique letters',
      },
    ],
    inputPlaceholder: 'Enter text to encode...',
  },
];

/**
 * All Batch 2 tools combined
 */
export const BATCH2_TOOLS: Tool[] = [
  ...CONVERTER_TOOLS,
  ...COLOR_TOOLS,
  ...GENERATOR_TOOLS,
  ...CIPHER_TOOLS,
];

/**
 * Batch 2 tool count
 */
export const BATCH2_TOOL_COUNT = BATCH2_TOOLS.length;
